events { worker_connections 1024; }

http {
    include mime.types;

    upstream mfe_shell { server mfe-shell:3000; }
    upstream mfe_pedidos { server mfe-pedidos:3001; }
    upstream api_auth { server svc-auth:8000; }
    upstream api_pedidos { server svc-pedidos:8000; }
    upstream api_catalogo { server svc-catalogo:8000; }

    server {
        listen 80;

        location / { proxy_pass http://mfe_shell; }
        location /pedidos-app/ { proxy_pass http://mfe_pedidos; }
        
        location /api/auth/ { 
            proxy_pass http://api_auth/; 
            proxy_set_header Host $host;
        }
        location /api/pedidos/ { 
            proxy_pass http://api_pedidos/; 
            proxy_set_header Host $host;
        }
        location /api/catalogo/ { 
            proxy_pass http://api_catalogo/; 
            proxy_set_header Host $host;
        }
    }
}